#Cases
caseMagic = "Magic"
caseNormal = "Normal"
caseShovel = "Shovel"
caseCave = "Cave"

#Unite
nameAmazon = "Amazon"
nameDwarf = "Dwarf"
nameElf = "Elf"
nameGiant = "Giant"
nameHobbit = "Hobbit"
nameHumans = "Humans"
nameMago = "Mago"
nameOrc = "Orc"
nameRats = "Rats"
nameSkeletton = "Skeletton"
nameTriton = "Triton"
nameTroll = "Troll"
nameWizzard = "Wizzard"
nameZombie = "Zombie"
